-- settings-beacons.lua
-- Additional settings to make beacon properties configurable

data:extend({
	-- Standard Beacon settings
	{
		type = "int-setting",
		name = "ab-standard-beacon-supply-area-distance",
		setting_type = "startup",
		default_value = 3,
		minimum_value = 1,
		maximum_value = 10,
		order = "iba-a",
	},
	{
		type = "int-setting",
		name = "ab-standard-beacon-module-slots",
		setting_type = "startup",
		default_value = 2,
		minimum_value = 1,
		maximum_value = 12,
		order = "iba-b",
	},
	{
		type = "double-setting",
		name = "ab-standard-beacon-distribution-effectivity",
		setting_type = "startup",
		default_value = 0.5,
		minimum_value = 0.1,
		maximum_value = 2.0,
		order = "iba-c",
	},
	{
		type = "double-setting",
		name = "ab-standard-beacon-distribution-effectivity-bonus-per-quality-level",
		setting_type = "startup",
		default_value = 0.1,
		minimum_value = 0.0,
		maximum_value = 0.5,
		order = "iba-d",
	},

	-- Focused Beacon settings
	{
		type = "int-setting",
		name = "ab-focused-beacon-supply-area-distance",
		setting_type = "startup",
		default_value = 2,
		minimum_value = 1,
		maximum_value = 10,
		order = "ibc-a",
	},
	{
		type = "int-setting",
		name = "ab-focused-beacon-exclusion-range",
		setting_type = "startup",
		default_value = 1,
		minimum_value = 0,
		maximum_value = 10,
		order = "ibc-b",
	},
	{
		type = "int-setting",
		name = "ab-focused-beacon-module-slots",
		setting_type = "startup",
		default_value = 3,
		minimum_value = 1,
		maximum_value = 12,
		order = "ibc-c",
	},
	{
		type = "double-setting",
		name = "ab-focused-beacon-distribution-effectivity",
		setting_type = "startup",
		default_value = 0.75,
		minimum_value = 0.1,
		maximum_value = 2.0,
		order = "ibc-d",
	},
	{
		type = "double-setting",
		name = "ab-focused-beacon-distribution-effectivity-bonus-per-quality-level",
		setting_type = "startup",
		default_value = 0.1,
		minimum_value = 0.0,
		maximum_value = 0.5,
		order = "ibc-e",
	},

	-- Node Beacon additional settings (supply-area-distance already exists)
	{
		type = "int-setting",
		name = "ab-node-beacon-supply-area-distance",
		setting_type = "startup",
		default_value = 8,
		minimum_value = 3,
		maximum_value = 15,
		order = "ibd-a",
	},
	{
		type = "int-setting",
		name = "ab-node-beacon-exclusion-range",
		setting_type = "startup",
		default_value = 0,
		minimum_value = 0,
		maximum_value = 10,
		order = "ibd-b",
	},
	{
		type = "int-setting",
		name = "ab-node-beacon-module-slots",
		setting_type = "startup",
		default_value = 3,
		minimum_value = 1,
		maximum_value = 12,
		order = "ibd-c",
	},
	{
		type = "double-setting",
		name = "ab-node-beacon-distribution-effectivity",
		setting_type = "startup",
		default_value = 0.5,
		minimum_value = 0.1,
		maximum_value = 2.0,
		order = "ibd-d",
	},
	{
		type = "double-setting",
		name = "ab-node-beacon-distribution-effectivity-bonus-per-quality-level",
		setting_type = "startup",
		default_value = 0.1,
		minimum_value = 0.0,
		maximum_value = 0.5,
		order = "ibd-e",
	},

	-- Conflux Beacon settings
	{
		type = "int-setting",
		name = "ab-conflux-beacon-supply-area-distance",
		setting_type = "startup",
		default_value = 9,
		minimum_value = 3,
		maximum_value = 20,
		order = "ibe-a",
	},
	{
		type = "int-setting",
		name = "ab-conflux-beacon-exclusion-range",
		setting_type = "startup",
		default_value = 3,
		minimum_value = 0,
		maximum_value = 10,
		order = "ibe-b",
	},
	{
		type = "int-setting",
		name = "ab-conflux-beacon-module-slots",
		setting_type = "startup",
		default_value = 6,
		minimum_value = 1,
		maximum_value = 12,
		order = "ibe-c",
	},
	{
		type = "double-setting",
		name = "ab-conflux-beacon-distribution-effectivity",
		setting_type = "startup",
		default_value = 0.5,
		minimum_value = 0.1,
		maximum_value = 2.0,
		order = "ibe-d",
	},
	{
		type = "double-setting",
		name = "ab-conflux-beacon-distribution-effectivity-bonus-per-quality-level",
		setting_type = "startup",
		default_value = 0.1,
		minimum_value = 0.0,
		maximum_value = 0.5,
		order = "ibe-e",
	},

	-- Hub Beacon settings
	{
		type = "int-setting",
		name = "ab-hub-beacon-supply-area-distance",
		setting_type = "startup",
		default_value = 14,
		minimum_value = 5,
		maximum_value = 30,
		order = "ibf-a",
	},
	{
		type = "int-setting",
		name = "ab-hub-beacon-exclusion-range",
		setting_type = "startup",
		default_value = 20,
		minimum_value = 0,
		maximum_value = 30,
		order = "ibf-b",
	},
	{
		type = "int-setting",
		name = "ab-hub-beacon-module-slots",
		setting_type = "startup",
		default_value = 9,
		minimum_value = 1,
		maximum_value = 16,
		order = "ibf-c",
	},
	{
		type = "double-setting",
		name = "ab-hub-beacon-distribution-effectivity",
		setting_type = "startup",
		default_value = 0.5,
		minimum_value = 0.1,
		maximum_value = 2.0,
		order = "ibf-d",
	},
	{
		type = "double-setting",
		name = "ab-hub-beacon-distribution-effectivity-bonus-per-quality-level",
		setting_type = "startup",
		default_value = 0.1,
		minimum_value = 0.0,
		maximum_value = 0.5,
		order = "ibf-e",
	},

	-- Isolation Beacon settings
	{
		type = "int-setting",
		name = "ab-isolation-beacon-supply-area-distance",
		setting_type = "startup",
		default_value = 30,
		minimum_value = 10,
		maximum_value = 50,
		order = "ibg-a",
	},
	{
		type = "int-setting",
		name = "ab-isolation-beacon-exclusion-range",
		setting_type = "startup",
		default_value = 8,
		minimum_value = 0,
		maximum_value = 20,
		order = "ibg-b",
	},
	{
		type = "int-setting",
		name = "ab-isolation-beacon-module-slots",
		setting_type = "startup",
		default_value = 10,
		minimum_value = 1,
		maximum_value = 20,
		order = "ibg-c",
	},
	{
		type = "double-setting",
		name = "ab-isolation-beacon-distribution-effectivity",
		setting_type = "startup",
		default_value = 0.5,
		minimum_value = 0.1,
		maximum_value = 2.0,
		order = "ibg-d",
	},
	{
		type = "double-setting",
		name = "ab-isolation-beacon-distribution-effectivity-bonus-per-quality-level",
		setting_type = "startup",
		default_value = 0.1,
		minimum_value = 0.0,
		maximum_value = 0.5,
		order = "ibg-e",
	},
	{
		type = "bool-setting",
		name = "ab-isolation-beacon-size-six",
		setting_type = "startup",
		default_value = false,
		order = "ibg-f",
	},
})
